--- #YAML:1.0
name:                Array-Slice
version:             0.01
abstract:            context-dependent array iterator
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Want:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Dmitry Karasik <dmitry@karasik.eu.org>
